spring:
  application.name: jobber
  datasource:
    url: jdbc:postgresql://localhost:5432/jobberdb
    username: postgres
    password: admin
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com   # REPLACE THIS
    password: your-app-password      # REPLACE THIS (Use App Password, not login password)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server.port: 8080