spring:
  application.name: jobber
  datasource:
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: ${DB_PASS}
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true


server.port: 8080