name: Auto Comment on Issuename: Auto Comment on Issue



on:on:

  issues:  issues:

    types: [opened]    types: [opened]



permissions:permissions:

  issues: write  issues: write



jobs:jobs:

  comment:  comment:

    runs-on: ubuntu-latest    runs-on: ubuntu-latest

    steps:    steps:

      - name: Add Comment to Issue      - name: Add Comment to Issue

        uses: actions/github-script@v6        uses: actions/github-script@v6

        with:        with:

          script: |          script: |

            const issueNumber = context.issue.number;            const issueNumber = context.issue.number;



            const commentBody1 = `### Thank you for raising this issue!            const commentBody1 = `### Thank you for raising this issue!\n We'll review it as soon as possible. We truly appreciate your contributions! âœ¨\n\n> Meanwhile make sure you've visited the README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md before creating a PR for this. Also, please do NOT create a PR until this issue has been assigned to you. ðŸ˜Š`;

            We'll review it as soon as possible. We truly appreciate your contributions! âœ¨



            > Meanwhile make sure you've visited the README.md, CONTRIBUTING.md, and CODE_OF_CONDUCT.md before creating a PR for this. Also, please do NOT create a PR until this issue has been assigned to you. ðŸ˜Š`;            await github.rest.issues.createComment({

              owner: context.repo.owner,

            await github.rest.issues.createComment({              repo: context.repo.repo,

              owner: context.repo.owner,              issue_number: issueNumber,

              repo: context.repo.repo,              body: commentBody1

              issue_number: issueNumber,            });

              body: commentBody1

            });            console.log('Comment added successfully.');

        
            console.log('Comment added successfully.');